name: Deploy to Google Cloud Run

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Optional branch to deploy (overrides push ref)'
        required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set branch variables
        id: vars
        run: |
          if [ -n "${{ github.event.inputs.branch }}" ]; then
            BRANCH="${{ github.event.inputs.branch }}"
          else
            BRANCH="${GITHUB_REF#refs/heads/}"
          fi
          SAFE_BRANCH=$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]' | tr '/_' '-' | sed 's/[^a-z0-9-]//g' | cut -c1-50)
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "safe_branch=$SAFE_BRANCH" >> $GITHUB_OUTPUT

      - name: Check required secrets and variables
        run: |
          echo "Checking presence of required secrets/variables..."
          missing=0
          check_required() {
            if [ -z "$1" ]; then
              echo "  $2: MISSING"
              missing=1
            else
              echo "  $2: SET"
            fi
          }
          check_required "${{ secrets.GCP_SA_KEY }}" "GCP_SA_KEY"
          check_required "${{ vars.GCP_PROJECT }}" "GCP_PROJECT"
          check_required "${{ vars.CLOUD_RUN_REGION }}" "CLOUD_RUN_REGION"
          check_required "${{ vars.CLOUD_RUN_SERVICE }}" "CLOUD_RUN_SERVICE"
          check_required "${{ vars.MODEL_URI }}" "MODEL_URI"
          check_required "${{ vars.METADATA_URI }}" "METADATA_URI"
          check_required "${{ vars.ANIME_CSV_URI }}" "ANIME_CSV_URI"
          check_required "${{ vars.USER_REVIEW_CSV_URI }}" "USER_REVIEW_CSV_URI"

          echo ""
          if [ "$missing" -ne 0 ]; then
            echo "One or more required secrets/variables are missing. Failing the job."
            exit 1
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set project
        run: gcloud config set project ${{ vars.GCP_PROJECT }}

      - name: Configure Docker to use gcloud auth
        run: gcloud auth configure-docker --quiet

      - name: Ensure Artifact Registry exists (if using Artifact Registry)
        run: |
          gcloud artifacts repositories create anime-images --repository-format=docker --location=${{ vars.CLOUD_RUN_REGION }} || true

      - name: Build and push Docker image (Artifact Registry)
        id: build-image
        env:
          BRANCH: ${{ steps.vars.outputs.branch }}
          SAFE_BRANCH: ${{ steps.vars.outputs.safe_branch }}
        run: |
          IMAGE_TAG="${SAFE_BRANCH}-${{ github.sha }}"
          IMAGE="${{ vars.CLOUD_RUN_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/animereco-images/anime-recommendation-backend:${IMAGE_TAG}"
          docker build -t "$IMAGE" -f api/Dockerfile .
          docker push "$IMAGE"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Deploy to Cloud Run (per-branch service)
        env:
          BRANCH: ${{ steps.vars.outputs.branch }}
          SAFE_BRANCH: ${{ steps.vars.outputs.safe_branch }}
        run: |
          BASE_SERVICE="${{ vars.CLOUD_RUN_SERVICE }}"
          if [ "$BRANCH" = "master" ]; then
            SERVICE_NAME="$BASE_SERVICE"
          else
            SERVICE_NAME="${BASE_SERVICE}-${SAFE_BRANCH}"
          fi

          IMAGE="${{ steps.build-image.outputs.image }}"

          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE" \
            --region ${{ vars.CLOUD_RUN_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --memory ${MEMORY:-4Gi} \
            --port 8000 \
            --timeout ${TIMEOUT:-10m} \
            --quiet \
            --set-env-vars MODEL_URI=${{ vars.MODEL_URI }},METADATA_URI=${{ vars.METADATA_URI }},ANIME_CSV_URI=${{ vars.ANIME_CSV_URI }},USER_REVIEW_CSV_URI=${{ vars.USER_REVIEW_CSV_URI }}
