name: Deploy API to Google Cloud Run

on:
  push:
    branches: [ 'master' ]
    paths:
      - 'api/**'
      - '.github/workflows/deploy-api-cloud-run.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check required secrets and variables
        run: |
          echo "Checking presence of required secrets/variables..."
          missing=0
          check_required() {
            if [ -z "$1" ]; then
              echo "  $2: MISSING"
              missing=1
            else
              echo "  $2: SET"
            fi
          }
          check_required "${{ secrets.GCP_SA_KEY }}" "GCP_SA_KEY"
          check_required "${{ vars.GCP_PROJECT }}" "GCP_PROJECT"
          check_required "${{ vars.CLOUD_RUN_REGION }}" "CLOUD_RUN_REGION"
          check_required "${{ vars.CLOUD_RUN_SERVICE }}" "CLOUD_RUN_SERVICE"
          check_required "${{ vars.MODEL_URI }}" "MODEL_URI"
          check_required "${{ vars.METADATA_URI }}" "METADATA_URI"
          check_required "${{ vars.ANIME_CSV_URI }}" "ANIME_CSV_URI"
          check_required "${{ vars.USER_REVIEW_CSV_URI }}" "USER_REVIEW_CSV_URI"
          check_required "${{ vars.ALLOWED_ORIGINS }}" "ALLOWED_ORIGINS"

          echo ""
          if [ "$missing" -ne 0 ]; then
            echo "One or more required secrets/variables are missing. Failing the job."
            exit 1
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set project
        run: gcloud config set project ${{ vars.GCP_PROJECT }}

      - name: Configure Docker to use gcloud auth
        run: gcloud auth configure-docker ${{ vars.CLOUD_RUN_REGION }}-docker.pkg.dev --quiet

      - name: Ensure Artifact Registry exists (if using Artifact Registry)
        run: |
          gcloud artifacts repositories create animereco-images --repository-format=docker --location=${{ vars.CLOUD_RUN_REGION }} || true

      - name: Build and push Docker image (Artifact Registry)
        id: build-image
        run: |
          IMAGE_TAG="master-${{ github.sha }}"
          IMAGE="${{ vars.CLOUD_RUN_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/animereco-images/anime-recommendation-backend:${IMAGE_TAG}"
          docker build -t "$IMAGE" -f Dockerfile api/
          docker push "$IMAGE"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Deploy to Cloud Run
        run: |
          IMAGE="${{ steps.build-image.outputs.image }}"

          gcloud run deploy ${{ vars.CLOUD_RUN_SERVICE }} \
            --image "$IMAGE" \
            --region ${{ vars.CLOUD_RUN_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --memory ${MEMORY:-4Gi} \
            --port 8000 \
            --timeout ${TIMEOUT:-10m} \
            --quiet \
            --set-env-vars MODEL_URI=${{ vars.MODEL_URI }},METADATA_URI=${{ vars.METADATA_URI }},ANIME_CSV_URI=${{ vars.ANIME_CSV_URI }},USER_REVIEW_CSV_URI=${{ vars.USER_REVIEW_CSV_URI }},ALLOWED_ORIGINS=${{ vars.ALLOWED_ORIGINS }}
