name: Deploy UI to Google Cloud Run

on:
  push:
    branches: [ 'master' ]
    paths:
      - 'anime-recommendation-ui/**'
      - '.github/workflows/deploy-ui-cloud-run.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check required secrets and variables
        run: |
          echo "Checking presence of required secrets/variables..."
          missing=0
          check_required() {
            if [ -z "$1" ]; then
              echo "  $2: MISSING"
              missing=1
            else
              echo "  $2: SET"
            fi
          }
          check_required "${{ secrets.GCP_SA_KEY }}" "GCP_SA_KEY"
          check_required "${{ vars.GCP_PROJECT }}" "GCP_PROJECT"
          check_required "${{ vars.CLOUD_RUN_REGION }}" "CLOUD_RUN_REGION"

          echo ""
          if [ "$missing" -ne 0 ]; then
            echo "One or more required secrets/variables are missing. Failing the job."
            exit 1
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set project
        run: gcloud config set project ${{ vars.GCP_PROJECT }}

      - name: Configure Docker to use gcloud auth
        run: gcloud auth configure-docker ${{ vars.CLOUD_RUN_REGION }}-docker.pkg.dev --quiet

      - name: Ensure Artifact Registry exists
        run: |
          gcloud artifacts repositories create animereco-images --repository-format=docker --location=${{ vars.CLOUD_RUN_REGION }} || true

      - name: Build and push Docker image
        id: build-image
        run: |
          IMAGE_TAG="master-${{ github.sha }}"
          IMAGE="${{ vars.CLOUD_RUN_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/animereco-images/anime-recommendation-ui:${IMAGE_TAG}"
          docker build -t "$IMAGE" -f anime-recommendation-ui/Dockerfile anime-recommendation-ui/
          docker push "$IMAGE"
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Deploy to Cloud Run
        run: |
          IMAGE="${{ steps.build-image.outputs.image }}"

          gcloud run deploy animereco-ui \
            --image "$IMAGE" \
            --region ${{ vars.CLOUD_RUN_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --memory 256Mi \
            --port 8080 \
            --quiet
